/**
 * GAME REGISTRY
 * ─────────────
 * To add a new game, just push an entry to this array.
 * The hub reads from this list to render the game grid.
 *
 * Fields:
 *   id          – unique slug (also the folder name under /games/)
 *   title       – display name
 *   subtitle    – short tagline
 *   category    – "card" | "board" | "strategy" | "party"
 *   players     – e.g. "2–5"
 *   duration    – e.g. "30–60 min"
 *   icon        – emoji for the card
 *   accentColor – hex color for the card accent
 *   status      – "playable" | "coming-soon"
 */

const GAMES = [
         {
    id: "countdown",
    title: "Countdown",
    subtitle: "30 Seconds to prove how dumb you are!",
    category: "puzzle",
    players: "1",
    duration: "5-10 min",
    icon: "0️⃣",
    accentColor: "#e74c3c",
    status: "playable",
  }, 
             {
    id: "heat",
    title: "Heat",
    subtitle: "Pedal to the Metal",
    category: "board",
    players: "1-4",
    duration: "5-20 min",
    icon: "0️⃣",
    accentColor: "#e74c3c",
    status: "playable",
  }, 
    {
    id: "five-crowns",
    title: "Five Crowns",
    subtitle: "The Games Not Over Until the Kings go Wild!",
    category: "card",
    players: "2–6",
    duration: "45–90 min",
    icon: "👑",
    accentColor: "#c9a84c",
    status: "playable",
  },
      {
    id: "flip-seven-vengeance",
    title: "Flip 7",
    subtitle: "With a Vengeance!",
    category: "card",
    players: "3+",
    duration: "5-10 min",
    icon: "7️⃣",
    accentColor: "#c9a84c",
    status: "playable",
  },
  {
    id: "glory-to-rome",
    title: "Glory to Rome",
    subtitle: "Build the eternal city",
    category: "strategy",
    players: "2–5",
    duration: "45–90 min",
    icon: "🦅",
    accentColor: "#c9a84c",
    status: "playable",
  },
  {
    id: "shithead",
    title: "Bastard",
    subtitle: "Don't be the last one holding cards",
    category: "card",
    players: "2–5",
    duration: "5-15 min",
    icon: "💩",
    accentColor: "#c0392b",
    status: "playable",
  },
  {
    id: "lotr-deckbuilder",
    title: "Lord of the Rings Deckbuilder",
    subtitle: "Destroy the Ring",
    category: "strategy",
    players: "1",
    duration: "45–90 min",
    icon: "🧙‍♂️",
    accentColor: "#c9a84c",
    status: "playable",
  },
  {
    id: "five-hundred",
    title: "500",
    subtitle: "The classic trick-taking game",
    category: "card",
    players: "4",
    duration: "30–45 min",
    icon: "🃏",
    accentColor: "#2ecc71",
    status: "playable",
  },
     {
    id: "for-sale",
    title: "For Sale",
    subtitle: "The Game of Property and Prosperity",
    category: "card",
    players: "3-5",
    duration: "5-10 min",
    icon: "🏡",
    accentColor: "#2ecc71",
    status: "playable",
  }, 
           {
    id: "tipping",
    title: "Tipping Point",
    subtitle: "Game Show",
    category: "strategy",
    players: "1",
    duration: "10-20 min",
    icon: "🧙‍♂️",
    accentColor: "#c9a84c",
    status: "playable",
  },
  {
    id: "wotr-cardgame",
    title: "War of the Rings",
    subtitle: "The Card Game",
    category: "strategy",
    players: "1",
    duration: "45–90 min",
    icon: "🧙‍♂️",
    accentColor: "#c9a84c",
    status: "playable",
  },
     {
    id: "wotr",
    title: "War of the Rings",
    subtitle: "2nd Edition",
    category: "strategy",
    players: "1",
    duration: "45–90 min",
    icon: "🧙‍♂️",
    accentColor: "#c9a84c",
    status: "playable",
  },
  { 
    id: "escalate",
    title: "Trick Escalation Engine",
    subtitle: "Getting Higher and Higher",
    category: "strategy",
    players: "1",
    duration: "45–90 min",
    icon: "🏎️",
    accentColor: "#c9a84c",
    status: "playable",
  },
         {
    id: "yaniv",
    title: "Yaniv",
    subtitle: "Do you have the lowest score?",
    category: "card",
    players: "4",
    duration: "5-10 min",
    icon: "0️⃣",
    accentColor: "#e74c3c",
    status: "playable",
  }, 
                  {
    id: "crow",
    title: "Crow Flies",
    subtitle: "how far does a crow fly?",
    category: "card",
    players: "4",
    duration: "5-10 min",
    icon: "🐦‍⬛",
    accentColor: "#e74c3c",
    status: "playable",
  }, 
      {
    id: "diamonds",
    title: "Diamonds",
    subtitle: "A trick taking game",
    category: "card",
    players: "4",
    duration: "20–30 min",
    icon: "♦️",
    accentColor: "#e74c3c",
    status: "coming-soon",
  },
  {
    id: "hearts",
    title: "Hearts",
    subtitle: "Avoid the Queen at all costs",
    category: "card",
    players: "4",
    duration: "20–30 min",
    icon: "♥️",
    accentColor: "#e74c3c",
    status: "coming-soon",
  },
 {
    id: "spades",
    title: "Spades",
    subtitle: "Bid, bluff & beat your rivals",
    category: "card",
    players: "4",
    duration: "20–40 min",
    icon: "♠️",
    accentColor: "#3498db",
    status: "coming-soon",
  },
];
