/* Generated by bakery/squeeze.py from board/board.json - do not edit. */
(typeof window !== "undefined" ? window : globalThis).BR_BOARD = {"file": "board.webp", "h": 1060.0, "small": "board_s.webp", "w": 1120.0, "x0": -60.0, "y0": -60.0};
