/* Generated by bakery/squeeze.py from regions/regions.json - do not edit. */
(typeof window !== "undefined" ? window : globalThis).BR_REGIONS = {
 "contract": {
  "arena": {
   "u0": -8.0,
   "u1": 8.0,
   "v0": -3.0,
   "v1": 4.2
  },
  "az": -32.0,
  "el": 24.0,
  "h": 1080,
  "ox": 960,
  "oy": 700,
  "ppm": 100,
  "w": 1920,
  "water": {
   "moor": 7.0,
   "v0": 5.4,
   "v1": 9.2,
   "z": -0.12
  }
 },
 "regions": {
  "andlang": {
   "dust": "#d2cdc0",
   "fog": "#dcd7dc",
   "rag": true,
   "realm": "alfheim",
   "sig": "spires",
   "water": true
  },
  "anger": {
   "dust": "#b19c78",
   "fog": "#c7ccb6",
   "rag": true,
   "realm": "manheim",
   "sig": "ironwood",
   "water": true
  },
  "elvagar": {
   "dust": "#b19c78",
   "fog": "#c7ccb6",
   "rag": true,
   "realm": "manheim",
   "sig": "stones",
   "water": true
  },
  "gimle": {
   "dust": "#d2cdc0",
   "fog": "#dcd7dc",
   "rag": true,
   "realm": "alfheim",
   "sig": "goldhall",
   "water": true
  },
  "horgr": {
   "dust": "#eef4f8",
   "fog": "#d2dde8",
   "rag": true,
   "realm": "jotunheim",
   "sig": "altar",
   "water": true
  },
  "musp": {
   "dust": "#5d544f",
   "fog": "#9c7466",
   "rag": true,
   "realm": "jotunheim",
   "sig": "lava",
   "water": true
  },
  "myrk": {
   "dust": "#8a7a60",
   "fog": "#8f9aa0",
   "rag": true,
   "realm": "manheim",
   "sig": "darkwood",
   "water": true
  },
  "utgard": {
   "dust": "#eef4f8",
   "fog": "#d2dde8",
   "rag": true,
   "realm": "jotunheim",
   "sig": "walls",
   "water": true
  },
  "ygg": {
   "dust": "#8f7f5b",
   "fog": "#b9c7aa",
   "realm": "ygg",
   "sig": "tree",
   "water": false
  }
 }
};
